---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint

platforms:
  - name: redesign
    box: redesign/centos7
    box_url: https://app.vagrantup.com/redesign/boxes/centos7
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 4444, host: 4444"
    memory: 4096
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: dhcp
      - auto_config: true
        ip: 192.168.10.22
        network_name: private_network
        type: static

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: goss
  lint:
    name: yamllint
