---

- src: https://github.com/dockpack/base_epel.git
  version: master
  name: dockpack.base_epel

- src: https://github.com/dockpack/base_docker.git
  version: master
  name: dockpack.base_docker

- src: https://github.com/dockpack/base_goss.git
  version: master
  name: dockpack.base_goss
